#!/bin/bash -e

# Copy the kernel image to be signed to the present working directory.
cp /boot/vmlinuz-linux vmlinuz-linux

# sign the image and overwrite the original with the signed copy.
echo -n "vmlinuz-linux - " && sbsign --key /root/keys/db.key --cert /root/keys/db.crt --output /boot/vmlinuz-linux vmlinuz-linux

# Make sure the new signed image is larger than the copy of the original.
# Since the signing process adds the signature to the file itself, the new image should be slightly larger.
# If the new image is not larger, this if will trigger and copy back the original image so that the computer isn't rendered unbootable.
# Obviously this can't protect from a corrupted image, but at least it's better than no checks at all.
if [[ $(du -b /boot/vmlinuz-linux | cut -f1) -lt $(du -b vmlinuz-linux | cut -f1) ]]; then
  cp vmlinuz-linux /boot/vmlinuz-linux
  echo "ERROR! Failed to sign kernel image for secure boot! Original image retained."
fi

# Remove the copy of the original image in the present working directory.
rm vmlinuz-linux